#!/bin/bash
while [ 1 -eq 1 ]
do
	/home/ginko/Documents/scripts/wifi/./reset-wifi
	rfkill unblock wifi
	killall -quiet wpa_supplicant
	ip link set wlp3s0 down
	ip link set wlp3s0 up

	names=$(iw dev wlp3s0 scan | grep SSID)

		
	case "$names" in
		*Ginko*)
			target=Phone
			;;
		"*Fra Vik*")
			target=fra
			;;
		*Fiorenza*)
			target=Fiorenza
			;;
		*Ecla*)
			target=Ecla
			;;
		*Ilaria*)
			target=ila
			;;
		*OnePlus3*)
			target=erus
			;;
		*FASTWEB-RXN261*)
			target=bolzano
			;;
		*FASTWEB-1-00219*)
			target=maddi
			;;
		*UpCycle*)
			target=upcycle
			;;
		*EOLO*)
			target=eolo
			;;
		*extender*)
			target=eolo-extender
			;;
		*TISCALI_6C96*)
			target=tuck
			;;
		"*WOW FI - FASTWEB")
			target=wowfi
			;;
		*eduroam*)
			target=eduroam
			;;
		*)
			target=0
			;;
	esac

	case $target in
		0)
			echo "[!] No Connection Aviable!"
			exit 1
			;;
		Ecla)
			echo "[*] Connecting to Ecla 2.4ghz"
			iw dev wlp3s0 disconnect
			connectionOutput=$(iw dev wlp3s0 connect 'Team Ecla 2.4ghz')
			;;
		*)
			echo "[*] Connecting to $target"
			connectionOutput=$(wpa_supplicant -B -i wlp3s0 -c /etc/wpa_supplicant/$target.conf)
			;;
	esac


	case $connectionOutput in 
		*p2p)
			echo "[!] Not connected, kill wpa_supplicant?"
			exit 1
			;;
		*Successfully*)
			echo "[*] Connecting..."
			;;
		*)
			case $target in
				Ecla)
					echo "[*] Wait!"
					;;
				*)
					echo "[!] Not connected, turn on Hotspot?"
					exit 1
					;;
			esac
			;;
	esac

	systemctl start dhcpcd > /dev/null 2>&1
	pid=$!
	wait $pid

	disconnected=1

	while [ $disconnected -eq 1 ]
	do
	    sleep 5
		wget -q --spider google.com
		connected=$?
	    case $connected in
	        0)
	            echo "[*] Online!"
				disconnected=0
	            ;;
	        *)
	            echo "[!] Offline"
	            echo "[!] Trying again..."
				sleep 10
				disconnected=0
	            ;;
	    esac
	done

	while [ $disconnected -eq 0 ]
	do
	    sleep 5
	    wget -q --spider google.com
	    connected=$?
	    case $connected in
	        0)
	            echo "[*] Still Online!"
	            ;;
	        *)
	            echo "[!] Signal Lost"
	            echo "[!] Restarting..."
				disconnected=1
	            ;;
	    esac
	done

done
