#!/bin/bash


### pacman

/usr/bin/pacman -Qe > /home/ginko/.backup/packages.txt


### python

source /home/ginko/.virtualenvs/env/bin/activate

/home/ginko/.virtualenvs/env/bin/pip freeze > /home/ginko/.backup/requirements.txt
deactivate


### suckless

# dwm

cd $HOME/Packs/dwm-git/src/dwm/ 
git checkout my_dwm 
git add -u 
git commit -m 'automatic commit' --untracked-files=no
git diff master > $HOME/.backup/dwm-patch.diff

# st

cd $HOME/Packs/st-git/src/st/ 
git checkout my_st 
git add -u 
git commit -m 'automatic commit' --untracked-files=no
git diff master > $HOME/.backup/st-patch.diff

# slstatus

cd $HOME/Packs/slstatus-git/src/slstatus/ 
git checkout my_slstatus 
git add -u 
git commit -m 'automatic commit' --untracked-files=no
git diff master > $HOME/.backup/slstatus-patch.diff

# dmenu

cd $HOME/Packs/dmenu-git/src/dmenu/ 
git checkout my_dmenu 
git add -u 
git commit -m 'automatic commit' --untracked-files=no
git diff master > $HOME/.backup/dmenu-patch.diff


###  dots 

cd $HOME

git --git-dir=$HOME/.dots/ --work-tree=$HOME add -u
git --git-dir=$HOME/.dots/ --work-tree=$HOME commit -m 'automatic commit'


# scripts

cd $HOME/Documents/scripts 
git add .
git commit -m 'automatic commit'


# projects

cd $HOME/Documents/projects

git add .
git commit -m 'automatic commit'


# notes

cd $HOME/Documents/notes

git add .
git commit -m 'automatic commit'



dunstify -u low "Every git repo is up to date" 

