#!/bin/sh

case $1 in
    Clean)
        efibootmgr --disk /dev/mmcblk1 --part 1 --create --label "Clean boot" --loader /vmlinuz-linux --unicode 'root=PARTUUID=8c7ca56b-08d0-4227-9c31-7cb51f330fcd rw initrd=\initramfs-linux.img quiet loglevel=3 rd.systemd.show_status=auto rd.udev.log_priority=3 vga=current i915.fastboot=1' --verbose
    ;;
    Verbose)
        efibootmgr --disk /dev/mmcblk1 --part 1 --create --label "Verbose boot" --loader /vmlinuz-linux --unicode 'root=PARTUUID=8c7ca56b-08d0-4227-9c31-7cb51f330fcd rw initrd=\initramfs-linux.img' --verbose
    ;;
    Experimental)
        exit 0
    ;;
esac


