#!/bin/bash

# dwm

cd $HOME/Packs/dwm-git/src/dwm/ 
git checkout my_dwm 
git add -u 
git commit -m 'automatic commit' --untracked-files=no
git diff master > $HOME/.backup/dwm-patch.diff

# st

cd $HOME/Packs/st-git/src/st/ 
git checkout my_st 
git add -u 
git commit -m 'automatic commit' --untracked-files=no
git diff master > $HOME/.backup/st-patch.diff

# slstatus

cd $HOME/Packs/slstatus-git/src/slstatus/ 
git checkout my_slstatus 
git add -u 
git commit -m 'automatic commit' --untracked-files=no
git diff master > $HOME/.backup/slstatus-patch.diff

# dmenu

cd $HOME/Packs/dmenu-git/src/dmenu/ 
git checkout my_dmenu 
git add -u 
git commit -m 'automatic commit' --untracked-files=no
git diff master > $HOME/.backup/dmenu-patch.diff
