#!/bin/sh
path=/sys/class/backlight/intel_backlight

max() {
	cat "$path"/max_brightness
}

top=$(max)

brightness() {
	cat "$path"/actual_brightness
}

factor() {
	expr $top / 10
}

step=$(factor)

if [[ $(( $(brightness) - $step )) -le 0 ]]; then
	echo 0 > "$path"/brightness
else
	echo $(( $(brightness) - $step )) > "$path"/brightness
fi

send_notification() {
	current=$(brightness)
	bar=$(seq -s "" $(( (10 * $current) / $top  )) | sed 's/[0-9]//g')
	barempty=$(seq -s "⭘" $(( ( 11 - ((10 * $current) / $top )) )) | sed 's/[0-9]//g')
	# makoctl dismiss --all && \
		notify-send -c brightness -i display-brightness-symbolic.symbolic "$bar$barempty"
	}

correctly_notify() {
	current=$(brightness)
	if [[ $current -le $step ]]; then
		# makoctl dismiss --all && \
			notify-send -i display-brightness-symbolic.symbolic ""
				else
					send_notification
	fi
}

correctly_notify
