#!/bin/bash

envs="$(ls ~/.virtualenvs)"

if [ $# -eq 0 ]
  then
	echo "Pick your environment"
	echo "$envs"
	read -p "-> "
	source ~/.virtualenvs/$REPLY/bin/activate

else
	source ~/.virtualenvs/$1/bin/activate

fi 

